"""
Report Generator — creates a downloadable HTML ESG report from analysis results.
"""


def generate_html_report(result: dict) -> str:
    """Generate a polished HTML report from analysis results dict."""
    e = result.get("environmental_score", 0)
    s = result.get("social_score", 0)
    g = result.get("governance_score", 0)
    overall = result.get("overall_score", 0)
    rating = result.get("esg_rating", "N/A")

    def badge(score):
        if score >= 70: return "#d1fae5", "#065f46"
        if score >= 50: return "#fef3c7", "#92400e"
        return "#fee2e2", "#991b1b"

    def findings_html(items):
        return "".join(f"<li>{i}</li>" for i in items)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ESG Report — {result.get('company_name','Company')}</title>
<style>
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{ font-family: 'Segoe UI', sans-serif; background:#f8fafc; color:#1e293b; }}
  .header {{ background:linear-gradient(135deg,#0f4c35,#2eb87a); color:white; padding:40px; }}
  .header h1 {{ font-size:2rem; }}
  .header p {{ opacity:.8; margin-top:6px; }}
  .container {{ max-width:1000px; margin:30px auto; padding:0 20px; }}
  .card {{ background:white; border-radius:12px; padding:24px; margin-bottom:24px;
           box-shadow:0 2px 8px rgba(0,0,0,.07); }}
  .scores {{ display:grid; grid-template-columns:repeat(4,1fr); gap:16px; }}
  .score-box {{ border-radius:10px; padding:20px; text-align:center; }}
  .score-box .num {{ font-size:2.5rem; font-weight:700; }}
  .score-box .label {{ font-size:.85rem; margin-top:4px; opacity:.7; }}
  h2 {{ font-size:1.2rem; color:#0f4c35; margin-bottom:12px; border-bottom:2px solid #e2e8f0; padding-bottom:8px; }}
  ul {{ padding-left:20px; line-height:1.8; }}
  .metrics {{ display:grid; grid-template-columns:repeat(3,1fr); gap:12px; }}
  .metric {{ background:#f0fdf4; border-radius:8px; padding:14px; }}
  .metric .val {{ font-size:1.3rem; font-weight:600; color:#0f4c35; }}
  .metric .key {{ font-size:.8rem; color:#64748b; margin-top:2px; }}
  .summary {{ background:#f0fdf4; border-left:4px solid #2eb87a; padding:16px 20px; border-radius:0 8px 8px 0; line-height:1.7; }}
  .risk {{ color:#b91c1c; }}
  footer {{ text-align:center; color:#94a3b8; font-size:.8rem; padding:30px 0; }}
</style>
</head>
<body>
<div class="header">
  <h1>🌿 ESG Analysis Report</h1>
  <p>{result.get('company_name','Company')} &bull; {result.get('report_year','2024')} &bull; Rating: <strong>{rating}</strong></p>
</div>

<div class="container">

  <div class="card">
    <h2>Executive Summary</h2>
    <p class="summary">{result.get('summary','')}</p>
  </div>

  <div class="card">
    <h2>ESG Scores</h2>
    <div class="scores">
      {"".join(
        f'<div class="score-box" style="background:{badge(sc)[0]};color:{badge(sc)[1]}">'
        f'<div class="num">{sc}</div><div class="label">{lb}</div></div>'
        for lb, sc in [("Overall", overall),("Environmental", e),("Social", s),("Governance", g)]
      )}
    </div>
  </div>

  <div class="card">
    <h2>🌍 Environmental Findings</h2>
    <ul>{findings_html(result.get('environmental_findings',[]))}</ul>
    <br>
    <div class="metrics">
      {"".join(f'<div class="metric"><div class="val">{v}</div><div class="key">{k}</div></div>'
               for k, v in result.get('environmental_metrics',{}).items())}
    </div>
  </div>

  <div class="card">
    <h2>👥 Social Findings</h2>
    <ul>{findings_html(result.get('social_findings',[]))}</ul>
  </div>

  <div class="card">
    <h2>🏛 Governance Findings</h2>
    <ul>{findings_html(result.get('governance_findings',[]))}</ul>
  </div>

  <div class="card">
    <h2>⚠️ Key Risks</h2>
    <ul class="risk">{findings_html(result.get('key_risks',[]))}</ul>
  </div>

  <div class="card">
    <h2>💡 Recommendations</h2>
    <ul>{findings_html(result.get('recommendations',[]))}</ul>
  </div>

</div>
<footer>Generated by ESG Finance Report Analyzer &bull; Final Year Project</footer>
</body>
</html>"""
    return html
